apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rep-{{.Values.report_name}}-{{.Values.schema}}
  labels: &labels
    app: custom-reporting
spec:
  schedule: '{{.Values.schedule}}'
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels: *labels
    spec:
      template:
        metadata:
          labels: *labels
        spec:
          containers:
            - name: rep-{{.Values.report_name}}-{{.Values.schema}}-r
              image: {{.Values.image}}:{{.Values.image_tag}}
              imagePullPolicy: Always
              args:
                - "submit"
                - "--wait"
                - "--generate-name={{.Values.report_name}}-{{.Values.schema}}-"
                - "-p"
                - "queryString={{js .Values.sql}}"
                - "-p"
                - "reportName={{.Values.report_name}}"
                - "workflow.yaml"
          restartPolicy: Never
      backoffLimit: 1
